CREATE TABLE IF NOT EXISTS records (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        player_name TEXT NOT NULL,
        score INTEGER NOT NULL,
        difficulty INTEGER NOT NULL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);